provider: rke
major-version: 3
aws: true
env:
  AWS_REGION: us-west-2
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
