// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("rke");

export declare const debug: boolean;
Object.defineProperty(exports, "debug", {
    get() {
        return __config.getObject<boolean>("debug") ?? (utilities.getEnvBoolean("RKE_DEBUG") || false);
    },
    enumerable: true,
});

export declare const logFile: string | undefined;
Object.defineProperty(exports, "logFile", {
    get() {
        return __config.get("logFile") ?? utilities.getEnv("RKE_LOG_FILE");
    },
    enumerable: true,
});

