// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Outputs
{

    [OutputType]
    public sealed class ClusterNode
    {
        /// <summary>
        /// Address of Bastion Host (string)
        /// </summary>
        public readonly string Address;
        /// <summary>
        /// Docker socket on the node that will be used in tunneling (string)
        /// </summary>
        public readonly string? DockerSocket;
        /// <summary>
        /// Hostname override for node (string)
        /// </summary>
        public readonly string? HostnameOverride;
        /// <summary>
        /// Internal address that will be used for components communication (string)
        /// </summary>
        public readonly string? InternalAddress;
        /// <summary>
        /// Node labels (map)
        /// </summary>
        public readonly ImmutableDictionary<string, object>? Labels;
        /// <summary>
        /// Name of the host provisioned via docker machine (string)
        /// </summary>
        public readonly string? NodeName;
        /// <summary>
        /// SSH Port of Bastion Host. Default `22` (string)
        /// </summary>
        public readonly string? Port;
        /// <summary>
        /// Node roles in k8s cluster. `controlplane`, `etcd` and `worker` are supported. (list)
        /// </summary>
        public readonly ImmutableArray<string> Roles;
        public readonly string? RolesDeprecated;
        /// <summary>
        /// SSH Agent Auth enable (bool)
        /// </summary>
        public readonly bool? SshAgentAuth;
        /// <summary>
        /// SSH Certificate Key (string)
        /// </summary>
        public readonly string? SshCert;
        /// <summary>
        /// SSH Certificate Path (string)
        /// </summary>
        public readonly string? SshCertPath;
        /// <summary>
        /// SSH Private Key (string)
        /// </summary>
        public readonly string? SshKey;
        /// <summary>
        /// SSH Private Key Path (string)
        /// </summary>
        public readonly string? SshKeyPath;
        /// <summary>
        /// Node taints (list)
        /// </summary>
        public readonly ImmutableArray<Outputs.ClusterNodeTaint> Taints;
        /// <summary>
        /// SSH User to Bastion Host (string)
        /// </summary>
        public readonly string User;

        [OutputConstructor]
        private ClusterNode(
            string address,

            string? dockerSocket,

            string? hostnameOverride,

            string? internalAddress,

            ImmutableDictionary<string, object>? labels,

            string? nodeName,

            string? port,

            ImmutableArray<string> roles,

            string? rolesDeprecated,

            bool? sshAgentAuth,

            string? sshCert,

            string? sshCertPath,

            string? sshKey,

            string? sshKeyPath,

            ImmutableArray<Outputs.ClusterNodeTaint> taints,

            string user)
        {
            Address = address;
            DockerSocket = dockerSocket;
            HostnameOverride = hostnameOverride;
            InternalAddress = internalAddress;
            Labels = labels;
            NodeName = nodeName;
            Port = port;
            Roles = roles;
            RolesDeprecated = rolesDeprecated;
            SshAgentAuth = sshAgentAuth;
            SshCert = sshCert;
            SshCertPath = sshCertPath;
            SshKey = sshKey;
            SshKeyPath = sshKeyPath;
            Taints = taints;
            User = user;
        }
    }
}
