// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Outputs
{

    [OutputType]
    public sealed class ClusterCloudProviderVsphereCloudConfig
    {
        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        public readonly Outputs.ClusterCloudProviderVsphereCloudConfigDisk? Disk;
        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        public readonly Outputs.ClusterCloudProviderVsphereCloudConfigGlobal? Global;
        /// <summary>
        /// RKE k8s cluster network configuration (list maxitems:1)
        /// </summary>
        public readonly Outputs.ClusterCloudProviderVsphereCloudConfigNetwork? Network;
        /// <summary>
        /// (List)
        /// </summary>
        public readonly ImmutableArray<Outputs.ClusterCloudProviderVsphereCloudConfigVirtualCenter> VirtualCenters;
        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        public readonly Outputs.ClusterCloudProviderVsphereCloudConfigWorkspace Workspace;

        [OutputConstructor]
        private ClusterCloudProviderVsphereCloudConfig(
            Outputs.ClusterCloudProviderVsphereCloudConfigDisk? disk,

            Outputs.ClusterCloudProviderVsphereCloudConfigGlobal? global,

            Outputs.ClusterCloudProviderVsphereCloudConfigNetwork? network,

            ImmutableArray<Outputs.ClusterCloudProviderVsphereCloudConfigVirtualCenter> virtualCenters,

            Outputs.ClusterCloudProviderVsphereCloudConfigWorkspace workspace)
        {
            Disk = disk;
            Global = global;
            Network = network;
            VirtualCenters = virtualCenters;
            Workspace = workspace;
        }
    }
}
