// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Outputs
{

    [OutputType]
    public sealed class ClusterMonitoring
    {
        /// <summary>
        /// Node selector key pair
        /// </summary>
        public readonly ImmutableDictionary<string, string>? NodeSelector;
        /// <summary>
        /// Monitoring options
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Options;
        /// <summary>
        /// Monitoring provider
        /// </summary>
        public readonly string? Provider;

        [OutputConstructor]
        private ClusterMonitoring(
            ImmutableDictionary<string, string>? nodeSelector,

            ImmutableDictionary<string, string>? options,

            string? provider)
        {
            NodeSelector = nodeSelector;
            Options = options;
            Provider = provider;
        }
    }
}
