// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Outputs
{

    [OutputType]
    public sealed class ClusterNodeTaint
    {
        /// <summary>
        /// Taint effect. `NoExecute`, `NoSchedule` (default) and `PreferNoSchedule` are supported (string)
        /// </summary>
        public readonly string? Effect;
        /// <summary>
        /// Use service instead
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Taint value (string)
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private ClusterNodeTaint(
            string? effect,

            string key,

            string value)
        {
            Effect = effect;
            Key = key;
            Value = value;
        }
    }
}
