// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Outputs
{

    [OutputType]
    public sealed class ClusterUpgradeStrategy
    {
        /// <summary>
        /// RKE drain nodes. Default: `false` (bool)
        /// </summary>
        public readonly bool? Drain;
        /// <summary>
        /// RKE drain node input (list Maxitems: 1)
        /// </summary>
        public readonly Outputs.ClusterUpgradeStrategyDrainInput? DrainInput;
        /// <summary>
        /// RKE max unavailable controlplane nodes. Default: `1` (string)
        /// </summary>
        public readonly string? MaxUnavailableControlplane;
        /// <summary>
        /// RKE max unavailable worker nodes. Default: `10%` (string)
        /// </summary>
        public readonly string? MaxUnavailableWorker;

        [OutputConstructor]
        private ClusterUpgradeStrategy(
            bool? drain,

            Outputs.ClusterUpgradeStrategyDrainInput? drainInput,

            string? maxUnavailableControlplane,

            string? maxUnavailableWorker)
        {
            Drain = drain;
            DrainInput = drainInput;
            MaxUnavailableControlplane = maxUnavailableControlplane;
            MaxUnavailableWorker = maxUnavailableWorker;
        }
    }
}
