// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.rke.inputs.ClusterCloudProviderVsphereCloudConfigDiskArgs;
import com.pulumi.rke.inputs.ClusterCloudProviderVsphereCloudConfigGlobalArgs;
import com.pulumi.rke.inputs.ClusterCloudProviderVsphereCloudConfigNetworkArgs;
import com.pulumi.rke.inputs.ClusterCloudProviderVsphereCloudConfigVirtualCenterArgs;
import com.pulumi.rke.inputs.ClusterCloudProviderVsphereCloudConfigWorkspaceArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterCloudProviderVsphereCloudConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterCloudProviderVsphereCloudConfigArgs Empty = new ClusterCloudProviderVsphereCloudConfigArgs();

    /**
     * (list maxitems:1)
     * 
     */
    @Import(name="disk")
    private @Nullable Output<ClusterCloudProviderVsphereCloudConfigDiskArgs> disk;

    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterCloudProviderVsphereCloudConfigDiskArgs>> disk() {
        return Optional.ofNullable(this.disk);
    }

    /**
     * (list maxitems:1)
     * 
     */
    @Import(name="global")
    private @Nullable Output<ClusterCloudProviderVsphereCloudConfigGlobalArgs> global;

    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterCloudProviderVsphereCloudConfigGlobalArgs>> global() {
        return Optional.ofNullable(this.global);
    }

    /**
     * (list maxitems:1)
     * 
     */
    @Import(name="network")
    private @Nullable Output<ClusterCloudProviderVsphereCloudConfigNetworkArgs> network;

    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterCloudProviderVsphereCloudConfigNetworkArgs>> network() {
        return Optional.ofNullable(this.network);
    }

    /**
     * (List)
     * 
     */
    @Import(name="virtualCenters", required=true)
    private Output<List<ClusterCloudProviderVsphereCloudConfigVirtualCenterArgs>> virtualCenters;

    /**
     * @return (List)
     * 
     */
    public Output<List<ClusterCloudProviderVsphereCloudConfigVirtualCenterArgs>> virtualCenters() {
        return this.virtualCenters;
    }

    /**
     * (list maxitems:1)
     * 
     */
    @Import(name="workspace", required=true)
    private Output<ClusterCloudProviderVsphereCloudConfigWorkspaceArgs> workspace;

    /**
     * @return (list maxitems:1)
     * 
     */
    public Output<ClusterCloudProviderVsphereCloudConfigWorkspaceArgs> workspace() {
        return this.workspace;
    }

    private ClusterCloudProviderVsphereCloudConfigArgs() {}

    private ClusterCloudProviderVsphereCloudConfigArgs(ClusterCloudProviderVsphereCloudConfigArgs $) {
        this.disk = $.disk;
        this.global = $.global;
        this.network = $.network;
        this.virtualCenters = $.virtualCenters;
        this.workspace = $.workspace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterCloudProviderVsphereCloudConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterCloudProviderVsphereCloudConfigArgs $;

        public Builder() {
            $ = new ClusterCloudProviderVsphereCloudConfigArgs();
        }

        public Builder(ClusterCloudProviderVsphereCloudConfigArgs defaults) {
            $ = new ClusterCloudProviderVsphereCloudConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param disk (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder disk(@Nullable Output<ClusterCloudProviderVsphereCloudConfigDiskArgs> disk) {
            $.disk = disk;
            return this;
        }

        /**
         * @param disk (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder disk(ClusterCloudProviderVsphereCloudConfigDiskArgs disk) {
            return disk(Output.of(disk));
        }

        /**
         * @param global (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder global(@Nullable Output<ClusterCloudProviderVsphereCloudConfigGlobalArgs> global) {
            $.global = global;
            return this;
        }

        /**
         * @param global (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder global(ClusterCloudProviderVsphereCloudConfigGlobalArgs global) {
            return global(Output.of(global));
        }

        /**
         * @param network (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder network(@Nullable Output<ClusterCloudProviderVsphereCloudConfigNetworkArgs> network) {
            $.network = network;
            return this;
        }

        /**
         * @param network (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder network(ClusterCloudProviderVsphereCloudConfigNetworkArgs network) {
            return network(Output.of(network));
        }

        /**
         * @param virtualCenters (List)
         * 
         * @return builder
         * 
         */
        public Builder virtualCenters(Output<List<ClusterCloudProviderVsphereCloudConfigVirtualCenterArgs>> virtualCenters) {
            $.virtualCenters = virtualCenters;
            return this;
        }

        /**
         * @param virtualCenters (List)
         * 
         * @return builder
         * 
         */
        public Builder virtualCenters(List<ClusterCloudProviderVsphereCloudConfigVirtualCenterArgs> virtualCenters) {
            return virtualCenters(Output.of(virtualCenters));
        }

        /**
         * @param virtualCenters (List)
         * 
         * @return builder
         * 
         */
        public Builder virtualCenters(ClusterCloudProviderVsphereCloudConfigVirtualCenterArgs... virtualCenters) {
            return virtualCenters(List.of(virtualCenters));
        }

        /**
         * @param workspace (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder workspace(Output<ClusterCloudProviderVsphereCloudConfigWorkspaceArgs> workspace) {
            $.workspace = workspace;
            return this;
        }

        /**
         * @param workspace (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder workspace(ClusterCloudProviderVsphereCloudConfigWorkspaceArgs workspace) {
            return workspace(Output.of(workspace));
        }

        public ClusterCloudProviderVsphereCloudConfigArgs build() {
            $.virtualCenters = Objects.requireNonNull($.virtualCenters, "expected parameter 'virtualCenters' to be non-null");
            $.workspace = Objects.requireNonNull($.workspace, "expected parameter 'workspace' to be non-null");
            return $;
        }
    }

}
