// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterAuthenticationWebhookArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterAuthenticationWebhookArgs Empty = new ClusterAuthenticationWebhookArgs();

    /**
     * Controls how long to cache authentication decisions (string)
     * 
     */
    @Import(name="cacheTimeout")
    private @Nullable Output<String> cacheTimeout;

    /**
     * @return Controls how long to cache authentication decisions (string)
     * 
     */
    public Optional<Output<String>> cacheTimeout() {
        return Optional.ofNullable(this.cacheTimeout);
    }

    /**
     * Multiline string that represent a custom webhook config file (string)
     * 
     */
    @Import(name="configFile")
    private @Nullable Output<String> configFile;

    /**
     * @return Multiline string that represent a custom webhook config file (string)
     * 
     */
    public Optional<Output<String>> configFile() {
        return Optional.ofNullable(this.configFile);
    }

    private ClusterAuthenticationWebhookArgs() {}

    private ClusterAuthenticationWebhookArgs(ClusterAuthenticationWebhookArgs $) {
        this.cacheTimeout = $.cacheTimeout;
        this.configFile = $.configFile;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterAuthenticationWebhookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterAuthenticationWebhookArgs $;

        public Builder() {
            $ = new ClusterAuthenticationWebhookArgs();
        }

        public Builder(ClusterAuthenticationWebhookArgs defaults) {
            $ = new ClusterAuthenticationWebhookArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cacheTimeout Controls how long to cache authentication decisions (string)
         * 
         * @return builder
         * 
         */
        public Builder cacheTimeout(@Nullable Output<String> cacheTimeout) {
            $.cacheTimeout = cacheTimeout;
            return this;
        }

        /**
         * @param cacheTimeout Controls how long to cache authentication decisions (string)
         * 
         * @return builder
         * 
         */
        public Builder cacheTimeout(String cacheTimeout) {
            return cacheTimeout(Output.of(cacheTimeout));
        }

        /**
         * @param configFile Multiline string that represent a custom webhook config file (string)
         * 
         * @return builder
         * 
         */
        public Builder configFile(@Nullable Output<String> configFile) {
            $.configFile = configFile;
            return this;
        }

        /**
         * @param configFile Multiline string that represent a custom webhook config file (string)
         * 
         * @return builder
         * 
         */
        public Builder configFile(String configFile) {
            return configFile(Output.of(configFile));
        }

        public ClusterAuthenticationWebhookArgs build() {
            return $;
        }
    }

}
