// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.rke.inputs.ClusterAuthenticationArgs;
import com.pulumi.rke.inputs.ClusterAuthorizationArgs;
import com.pulumi.rke.inputs.ClusterBastionHostArgs;
import com.pulumi.rke.inputs.ClusterCertificateArgs;
import com.pulumi.rke.inputs.ClusterCloudProviderArgs;
import com.pulumi.rke.inputs.ClusterControlPlaneHostArgs;
import com.pulumi.rke.inputs.ClusterDnsArgs;
import com.pulumi.rke.inputs.ClusterEtcdHostArgs;
import com.pulumi.rke.inputs.ClusterInactiveHostArgs;
import com.pulumi.rke.inputs.ClusterIngressArgs;
import com.pulumi.rke.inputs.ClusterMonitoringArgs;
import com.pulumi.rke.inputs.ClusterNetworkArgs;
import com.pulumi.rke.inputs.ClusterNodeArgs;
import com.pulumi.rke.inputs.ClusterPrivateRegistryArgs;
import com.pulumi.rke.inputs.ClusterRestoreArgs;
import com.pulumi.rke.inputs.ClusterRotateCertificatesArgs;
import com.pulumi.rke.inputs.ClusterRunningSystemImageArgs;
import com.pulumi.rke.inputs.ClusterServicesArgs;
import com.pulumi.rke.inputs.ClusterServicesEtcdDeprecatedArgs;
import com.pulumi.rke.inputs.ClusterServicesKubeApiDeprecatedArgs;
import com.pulumi.rke.inputs.ClusterServicesKubeControllerDeprecatedArgs;
import com.pulumi.rke.inputs.ClusterServicesKubeProxyDeprecatedArgs;
import com.pulumi.rke.inputs.ClusterServicesKubeSchedulerDeprecatedArgs;
import com.pulumi.rke.inputs.ClusterServicesKubeletDeprecatedArgs;
import com.pulumi.rke.inputs.ClusterSystemImagesArgs;
import com.pulumi.rke.inputs.ClusterUpgradeStrategyArgs;
import com.pulumi.rke.inputs.ClusterWorkerHostArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterState extends com.pulumi.resources.ResourceArgs {

    public static final ClusterState Empty = new ClusterState();

    /**
     * RKE k8s cluster addon deployment timeout in seconds for status check (int)
     * 
     */
    @Import(name="addonJobTimeout")
    private @Nullable Output<Integer> addonJobTimeout;

    /**
     * @return RKE k8s cluster addon deployment timeout in seconds for status check (int)
     * 
     */
    public Optional<Output<Integer>> addonJobTimeout() {
        return Optional.ofNullable(this.addonJobTimeout);
    }

    /**
     * RKE k8s cluster user addons YAML manifest to be deployed (string)
     * 
     */
    @Import(name="addons")
    private @Nullable Output<String> addons;

    /**
     * @return RKE k8s cluster user addons YAML manifest to be deployed (string)
     * 
     */
    public Optional<Output<String>> addons() {
        return Optional.ofNullable(this.addons);
    }

    /**
     * RKE k8s cluster user addons YAML manifest urls or paths to be deployed (list)
     * 
     */
    @Import(name="addonsIncludes")
    private @Nullable Output<List<String>> addonsIncludes;

    /**
     * @return RKE k8s cluster user addons YAML manifest urls or paths to be deployed (list)
     * 
     */
    public Optional<Output<List<String>>> addonsIncludes() {
        return Optional.ofNullable(this.addonsIncludes);
    }

    /**
     * (Computed) RKE k8s cluster api server url (string)
     * 
     */
    @Import(name="apiServerUrl")
    private @Nullable Output<String> apiServerUrl;

    /**
     * @return (Computed) RKE k8s cluster api server url (string)
     * 
     */
    public Optional<Output<String>> apiServerUrl() {
        return Optional.ofNullable(this.apiServerUrl);
    }

    /**
     * RKE k8s cluster authentication configuration (list maxitems:1)
     * 
     */
    @Import(name="authentication")
    private @Nullable Output<ClusterAuthenticationArgs> authentication;

    /**
     * @return RKE k8s cluster authentication configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterAuthenticationArgs>> authentication() {
        return Optional.ofNullable(this.authentication);
    }

    /**
     * RKE k8s cluster authorization mode configuration (list maxitems:1)
     * 
     */
    @Import(name="authorization")
    private @Nullable Output<ClusterAuthorizationArgs> authorization;

    /**
     * @return RKE k8s cluster authorization mode configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterAuthorizationArgs>> authorization() {
        return Optional.ofNullable(this.authorization);
    }

    /**
     * RKE k8s cluster bastion Host configuration (list maxitems:1)
     * 
     */
    @Import(name="bastionHost")
    private @Nullable Output<ClusterBastionHostArgs> bastionHost;

    /**
     * @return RKE k8s cluster bastion Host configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterBastionHostArgs>> bastionHost() {
        return Optional.ofNullable(this.bastionHost);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster CA certificate (string)
     * 
     */
    @Import(name="caCrt")
    private @Nullable Output<String> caCrt;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster CA certificate (string)
     * 
     */
    public Optional<Output<String>> caCrt() {
        return Optional.ofNullable(this.caCrt);
    }

    /**
     * Specify a certificate dir path (string)
     * 
     */
    @Import(name="certDir")
    private @Nullable Output<String> certDir;

    /**
     * @return Specify a certificate dir path (string)
     * 
     */
    public Optional<Output<String>> certDir() {
        return Optional.ofNullable(this.certDir);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster certificates (string)
     * 
     */
    @Import(name="certificates")
    private @Nullable Output<List<ClusterCertificateArgs>> certificates;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster certificates (string)
     * 
     */
    public Optional<Output<List<ClusterCertificateArgs>>> certificates() {
        return Optional.ofNullable(this.certificates);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster client certificate (string)
     * 
     */
    @Import(name="clientCert")
    private @Nullable Output<String> clientCert;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster client certificate (string)
     * 
     */
    public Optional<Output<String>> clientCert() {
        return Optional.ofNullable(this.clientCert);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster client key (string)
     * 
     */
    @Import(name="clientKey")
    private @Nullable Output<String> clientKey;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster client key (string)
     * 
     */
    public Optional<Output<String>> clientKey() {
        return Optional.ofNullable(this.clientKey);
    }

    /**
     * RKE k8s cluster cloud provider configuration [rke-cloud-providers](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/) (list maxitems:1)
     * 
     */
    @Import(name="cloudProvider")
    private @Nullable Output<ClusterCloudProviderArgs> cloudProvider;

    /**
     * @return RKE k8s cluster cloud provider configuration [rke-cloud-providers](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/) (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterCloudProviderArgs>> cloudProvider() {
        return Optional.ofNullable(this.cloudProvider);
    }

    /**
     * Cluster CIDR option for kube controller service (string)
     * 
     */
    @Import(name="clusterCidr")
    private @Nullable Output<String> clusterCidr;

    /**
     * @return Cluster CIDR option for kube controller service (string)
     * 
     */
    public Optional<Output<String>> clusterCidr() {
        return Optional.ofNullable(this.clusterCidr);
    }

    /**
     * Cluster DNS Server option for kubelet service (string)
     * 
     */
    @Import(name="clusterDnsServer")
    private @Nullable Output<String> clusterDnsServer;

    /**
     * @return Cluster DNS Server option for kubelet service (string)
     * 
     */
    public Optional<Output<String>> clusterDnsServer() {
        return Optional.ofNullable(this.clusterDnsServer);
    }

    /**
     * Cluster Domain option for kubelet service. Default `cluster.local` (string)
     * 
     */
    @Import(name="clusterDomain")
    private @Nullable Output<String> clusterDomain;

    /**
     * @return Cluster Domain option for kubelet service. Default `cluster.local` (string)
     * 
     */
    public Optional<Output<String>> clusterDomain() {
        return Optional.ofNullable(this.clusterDomain);
    }

    /**
     * RKE k8s cluster name used in the kube config (string)
     * 
     */
    @Import(name="clusterName")
    private @Nullable Output<String> clusterName;

    /**
     * @return RKE k8s cluster name used in the kube config (string)
     * 
     */
    public Optional<Output<String>> clusterName() {
        return Optional.ofNullable(this.clusterName);
    }

    /**
     * RKE k8s cluster config yaml encoded. Provider arguments take precedence over this one (string)
     * 
     */
    @Import(name="clusterYaml")
    private @Nullable Output<String> clusterYaml;

    /**
     * @return RKE k8s cluster config yaml encoded. Provider arguments take precedence over this one (string)
     * 
     */
    public Optional<Output<String>> clusterYaml() {
        return Optional.ofNullable(this.clusterYaml);
    }

    /**
     * (Computed) RKE k8s cluster control plane nodes (list)
     * 
     */
    @Import(name="controlPlaneHosts")
    private @Nullable Output<List<ClusterControlPlaneHostArgs>> controlPlaneHosts;

    /**
     * @return (Computed) RKE k8s cluster control plane nodes (list)
     * 
     */
    public Optional<Output<List<ClusterControlPlaneHostArgs>>> controlPlaneHosts() {
        return Optional.ofNullable(this.controlPlaneHosts);
    }

    /**
     * Use custom certificates from a cert dir (string)
     * 
     */
    @Import(name="customCerts")
    private @Nullable Output<Boolean> customCerts;

    /**
     * @return Use custom certificates from a cert dir (string)
     * 
     */
    public Optional<Output<Boolean>> customCerts() {
        return Optional.ofNullable(this.customCerts);
    }

    /**
     * RKE k8s cluster delay on creation (int)
     * 
     */
    @Import(name="delayOnCreation")
    private @Nullable Output<Integer> delayOnCreation;

    /**
     * @return RKE k8s cluster delay on creation (int)
     * 
     */
    public Optional<Output<Integer>> delayOnCreation() {
        return Optional.ofNullable(this.delayOnCreation);
    }

    /**
     * Deploy RKE cluster on a dind environment. Default: `false` (bool)
     * 
     */
    @Import(name="dind")
    private @Nullable Output<Boolean> dind;

    /**
     * @return Deploy RKE cluster on a dind environment. Default: `false` (bool)
     * 
     */
    public Optional<Output<Boolean>> dind() {
        return Optional.ofNullable(this.dind);
    }

    /**
     * DinD RKE cluster dns (string)
     * 
     */
    @Import(name="dindDnsServer")
    private @Nullable Output<String> dindDnsServer;

    /**
     * @return DinD RKE cluster dns (string)
     * 
     */
    public Optional<Output<String>> dindDnsServer() {
        return Optional.ofNullable(this.dindDnsServer);
    }

    /**
     * DinD RKE cluster storage driver (string)
     * 
     */
    @Import(name="dindStorageDriver")
    private @Nullable Output<String> dindStorageDriver;

    /**
     * @return DinD RKE cluster storage driver (string)
     * 
     */
    public Optional<Output<String>> dindStorageDriver() {
        return Optional.ofNullable(this.dindStorageDriver);
    }

    /**
     * Enable/Disable RKE k8s cluster port checking. Default `false` (bool)
     * 
     */
    @Import(name="disablePortCheck")
    private @Nullable Output<Boolean> disablePortCheck;

    /**
     * @return Enable/Disable RKE k8s cluster port checking. Default `false` (bool)
     * 
     */
    public Optional<Output<Boolean>> disablePortCheck() {
        return Optional.ofNullable(this.disablePortCheck);
    }

    /**
     * RKE k8s cluster DNS Config (list maxitems:1)
     * 
     */
    @Import(name="dns")
    private @Nullable Output<ClusterDnsArgs> dns;

    /**
     * @return RKE k8s cluster DNS Config (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterDnsArgs>> dns() {
        return Optional.ofNullable(this.dns);
    }

    /**
     * Enable/Disable CRI dockerd for kubelet; set it to true starting from Kubernetes version 1.24 or later. Default `false` (bool)
     * 
     */
    @Import(name="enableCriDockerd")
    private @Nullable Output<Boolean> enableCriDockerd;

    /**
     * @return Enable/Disable CRI dockerd for kubelet; set it to true starting from Kubernetes version 1.24 or later. Default `false` (bool)
     * 
     */
    public Optional<Output<Boolean>> enableCriDockerd() {
        return Optional.ofNullable(this.enableCriDockerd);
    }

    /**
     * (Computed) RKE k8s cluster etcd nodes (list)
     * 
     */
    @Import(name="etcdHosts")
    private @Nullable Output<List<ClusterEtcdHostArgs>> etcdHosts;

    /**
     * @return (Computed) RKE k8s cluster etcd nodes (list)
     * 
     */
    public Optional<Output<List<ClusterEtcdHostArgs>>> etcdHosts() {
        return Optional.ofNullable(this.etcdHosts);
    }

    /**
     * Enable/Disable RKE k8s cluster strict docker version checking. Default `false` (bool)
     * 
     */
    @Import(name="ignoreDockerVersion")
    private @Nullable Output<Boolean> ignoreDockerVersion;

    /**
     * @return Enable/Disable RKE k8s cluster strict docker version checking. Default `false` (bool)
     * 
     */
    public Optional<Output<Boolean>> ignoreDockerVersion() {
        return Optional.ofNullable(this.ignoreDockerVersion);
    }

    /**
     * (Computed) RKE k8s cluster inactive nodes (list)
     * 
     */
    @Import(name="inactiveHosts")
    private @Nullable Output<List<ClusterInactiveHostArgs>> inactiveHosts;

    /**
     * @return (Computed) RKE k8s cluster inactive nodes (list)
     * 
     */
    public Optional<Output<List<ClusterInactiveHostArgs>>> inactiveHosts() {
        return Optional.ofNullable(this.inactiveHosts);
    }

    /**
     * RKE k8s cluster ingress controller configuration (list maxitems:1)
     * 
     */
    @Import(name="ingress")
    private @Nullable Output<ClusterIngressArgs> ingress;

    /**
     * @return RKE k8s cluster ingress controller configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterIngressArgs>> ingress() {
        return Optional.ofNullable(this.ingress);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster internal kube config yaml (string)
     * 
     * @deprecated
     * Use kube_config_yaml instead
     * 
     */
    @Deprecated /* Use kube_config_yaml instead */
    @Import(name="internalKubeConfigYaml")
    private @Nullable Output<String> internalKubeConfigYaml;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster internal kube config yaml (string)
     * 
     * @deprecated
     * Use kube_config_yaml instead
     * 
     */
    @Deprecated /* Use kube_config_yaml instead */
    public Optional<Output<String>> internalKubeConfigYaml() {
        return Optional.ofNullable(this.internalKubeConfigYaml);
    }

    /**
     * (Computed) RKE k8s cluster admin user (string)
     * 
     */
    @Import(name="kubeAdminUser")
    private @Nullable Output<String> kubeAdminUser;

    /**
     * @return (Computed) RKE k8s cluster admin user (string)
     * 
     */
    public Optional<Output<String>> kubeAdminUser() {
        return Optional.ofNullable(this.kubeAdminUser);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster kube config yaml (string)
     * 
     */
    @Import(name="kubeConfigYaml")
    private @Nullable Output<String> kubeConfigYaml;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster kube config yaml (string)
     * 
     */
    public Optional<Output<String>> kubeConfigYaml() {
        return Optional.ofNullable(this.kubeConfigYaml);
    }

    /**
     * K8s version to deploy. If kubernetes image is specified, image version takes precedence. Default: `rke default` (string)
     * 
     */
    @Import(name="kubernetesVersion")
    private @Nullable Output<String> kubernetesVersion;

    /**
     * @return K8s version to deploy. If kubernetes image is specified, image version takes precedence. Default: `rke default` (string)
     * 
     */
    public Optional<Output<String>> kubernetesVersion() {
        return Optional.ofNullable(this.kubernetesVersion);
    }

    /**
     * RKE k8s cluster monitoring Config (list maxitems:1)
     * 
     */
    @Import(name="monitoring")
    private @Nullable Output<ClusterMonitoringArgs> monitoring;

    /**
     * @return RKE k8s cluster monitoring Config (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterMonitoringArgs>> monitoring() {
        return Optional.ofNullable(this.monitoring);
    }

    /**
     * RKE k8s cluster network configuration (list maxitems:1)
     * 
     */
    @Import(name="network")
    private @Nullable Output<ClusterNetworkArgs> network;

    /**
     * @return RKE k8s cluster network configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterNetworkArgs>> network() {
        return Optional.ofNullable(this.network);
    }

    /**
     * RKE k8s cluster nodes (list)
     * 
     */
    @Import(name="nodes")
    private @Nullable Output<List<ClusterNodeArgs>> nodes;

    /**
     * @return RKE k8s cluster nodes (list)
     * 
     */
    public Optional<Output<List<ClusterNodeArgs>>> nodes() {
        return Optional.ofNullable(this.nodes);
    }

    /**
     * @deprecated
     * Use cluster_yaml instead
     * 
     */
    @Deprecated /* Use cluster_yaml instead */
    @Import(name="nodesConfs")
    private @Nullable Output<List<String>> nodesConfs;

    /**
     * @deprecated
     * Use cluster_yaml instead
     * 
     */
    @Deprecated /* Use cluster_yaml instead */
    public Optional<Output<List<String>>> nodesConfs() {
        return Optional.ofNullable(this.nodesConfs);
    }

    /**
     * RKE k8s directory path (string)
     * 
     */
    @Import(name="prefixPath")
    private @Nullable Output<String> prefixPath;

    /**
     * @return RKE k8s directory path (string)
     * 
     */
    public Optional<Output<String>> prefixPath() {
        return Optional.ofNullable(this.prefixPath);
    }

    /**
     * RKE k8s cluster private docker registries (list)
     * 
     */
    @Import(name="privateRegistries")
    private @Nullable Output<List<ClusterPrivateRegistryArgs>> privateRegistries;

    /**
     * @return RKE k8s cluster private docker registries (list)
     * 
     */
    public Optional<Output<List<ClusterPrivateRegistryArgs>>> privateRegistries() {
        return Optional.ofNullable(this.privateRegistries);
    }

    /**
     * RKE k8s cluster restore configuration (list maxitems:1)
     * 
     */
    @Import(name="restore")
    private @Nullable Output<ClusterRestoreArgs> restore;

    /**
     * @return RKE k8s cluster restore configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterRestoreArgs>> restore() {
        return Optional.ofNullable(this.restore);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster config yaml (string)
     * 
     */
    @Import(name="rkeClusterYaml")
    private @Nullable Output<String> rkeClusterYaml;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster config yaml (string)
     * 
     */
    public Optional<Output<String>> rkeClusterYaml() {
        return Optional.ofNullable(this.rkeClusterYaml);
    }

    /**
     * (Computed/Sensitive) RKE k8s cluster state (string)
     * 
     */
    @Import(name="rkeState")
    private @Nullable Output<String> rkeState;

    /**
     * @return (Computed/Sensitive) RKE k8s cluster state (string)
     * 
     */
    public Optional<Output<String>> rkeState() {
        return Optional.ofNullable(this.rkeState);
    }

    /**
     * RKE k8s cluster rotate certificates configuration (list maxitems:1)
     * 
     */
    @Import(name="rotateCertificates")
    private @Nullable Output<ClusterRotateCertificatesArgs> rotateCertificates;

    /**
     * @return RKE k8s cluster rotate certificates configuration (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterRotateCertificatesArgs>> rotateCertificates() {
        return Optional.ofNullable(this.rotateCertificates);
    }

    /**
     * (Computed) RKE k8s cluster running system images list (list)
     * 
     */
    @Import(name="runningSystemImages")
    private @Nullable Output<List<ClusterRunningSystemImageArgs>> runningSystemImages;

    /**
     * @return (Computed) RKE k8s cluster running system images list (list)
     * 
     */
    public Optional<Output<List<ClusterRunningSystemImageArgs>>> runningSystemImages() {
        return Optional.ofNullable(this.runningSystemImages);
    }

    /**
     * RKE k8s cluster services (list maxitems:1)
     * 
     */
    @Import(name="services")
    private @Nullable Output<ClusterServicesArgs> services;

    /**
     * @return RKE k8s cluster services (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterServicesArgs>> services() {
        return Optional.ofNullable(this.services);
    }

    /**
     * Use services.etcd instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.etcd instead
     * 
     */
    @Deprecated /* Use services.etcd instead */
    @Import(name="servicesEtcdDeprecated")
    private @Nullable Output<ClusterServicesEtcdDeprecatedArgs> servicesEtcdDeprecated;

    /**
     * @return Use services.etcd instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.etcd instead
     * 
     */
    @Deprecated /* Use services.etcd instead */
    public Optional<Output<ClusterServicesEtcdDeprecatedArgs>> servicesEtcdDeprecated() {
        return Optional.ofNullable(this.servicesEtcdDeprecated);
    }

    /**
     * Use services.kube_api instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kube_api instead
     * 
     */
    @Deprecated /* Use services.kube_api instead */
    @Import(name="servicesKubeApiDeprecated")
    private @Nullable Output<ClusterServicesKubeApiDeprecatedArgs> servicesKubeApiDeprecated;

    /**
     * @return Use services.kube_api instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kube_api instead
     * 
     */
    @Deprecated /* Use services.kube_api instead */
    public Optional<Output<ClusterServicesKubeApiDeprecatedArgs>> servicesKubeApiDeprecated() {
        return Optional.ofNullable(this.servicesKubeApiDeprecated);
    }

    /**
     * Use services.kube_controller instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kube_controller instead
     * 
     */
    @Deprecated /* Use services.kube_controller instead */
    @Import(name="servicesKubeControllerDeprecated")
    private @Nullable Output<ClusterServicesKubeControllerDeprecatedArgs> servicesKubeControllerDeprecated;

    /**
     * @return Use services.kube_controller instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kube_controller instead
     * 
     */
    @Deprecated /* Use services.kube_controller instead */
    public Optional<Output<ClusterServicesKubeControllerDeprecatedArgs>> servicesKubeControllerDeprecated() {
        return Optional.ofNullable(this.servicesKubeControllerDeprecated);
    }

    /**
     * Use services.kubeproxy instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kubeproxy instead
     * 
     */
    @Deprecated /* Use services.kubeproxy instead */
    @Import(name="servicesKubeProxyDeprecated")
    private @Nullable Output<ClusterServicesKubeProxyDeprecatedArgs> servicesKubeProxyDeprecated;

    /**
     * @return Use services.kubeproxy instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kubeproxy instead
     * 
     */
    @Deprecated /* Use services.kubeproxy instead */
    public Optional<Output<ClusterServicesKubeProxyDeprecatedArgs>> servicesKubeProxyDeprecated() {
        return Optional.ofNullable(this.servicesKubeProxyDeprecated);
    }

    /**
     * Use services.scheduler instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.scheduler instead
     * 
     */
    @Deprecated /* Use services.scheduler instead */
    @Import(name="servicesKubeSchedulerDeprecated")
    private @Nullable Output<ClusterServicesKubeSchedulerDeprecatedArgs> servicesKubeSchedulerDeprecated;

    /**
     * @return Use services.scheduler instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.scheduler instead
     * 
     */
    @Deprecated /* Use services.scheduler instead */
    public Optional<Output<ClusterServicesKubeSchedulerDeprecatedArgs>> servicesKubeSchedulerDeprecated() {
        return Optional.ofNullable(this.servicesKubeSchedulerDeprecated);
    }

    /**
     * Use services.kubelet instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kubelet instead
     * 
     */
    @Deprecated /* Use services.kubelet instead */
    @Import(name="servicesKubeletDeprecated")
    private @Nullable Output<ClusterServicesKubeletDeprecatedArgs> servicesKubeletDeprecated;

    /**
     * @return Use services.kubelet instead (list maxitems:1)
     * 
     * @deprecated
     * Use services.kubelet instead
     * 
     */
    @Deprecated /* Use services.kubelet instead */
    public Optional<Output<ClusterServicesKubeletDeprecatedArgs>> servicesKubeletDeprecated() {
        return Optional.ofNullable(this.servicesKubeletDeprecated);
    }

    /**
     * SSH Agent Auth enable (bool)
     * 
     */
    @Import(name="sshAgentAuth")
    private @Nullable Output<Boolean> sshAgentAuth;

    /**
     * @return SSH Agent Auth enable (bool)
     * 
     */
    public Optional<Output<Boolean>> sshAgentAuth() {
        return Optional.ofNullable(this.sshAgentAuth);
    }

    /**
     * SSH Certificate Path (string)
     * 
     */
    @Import(name="sshCertPath")
    private @Nullable Output<String> sshCertPath;

    /**
     * @return SSH Certificate Path (string)
     * 
     */
    public Optional<Output<String>> sshCertPath() {
        return Optional.ofNullable(this.sshCertPath);
    }

    /**
     * SSH Private Key Path (string)
     * 
     */
    @Import(name="sshKeyPath")
    private @Nullable Output<String> sshKeyPath;

    /**
     * @return SSH Private Key Path (string)
     * 
     */
    public Optional<Output<String>> sshKeyPath() {
        return Optional.ofNullable(this.sshKeyPath);
    }

    /**
     * RKE k8s cluster system images list (list maxitems:1)
     * 
     */
    @Import(name="systemImages")
    private @Nullable Output<ClusterSystemImagesArgs> systemImages;

    /**
     * @return RKE k8s cluster system images list (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterSystemImagesArgs>> systemImages() {
        return Optional.ofNullable(this.systemImages);
    }

    /**
     * Skip idempotent deployment of control and etcd plane. Default `false` (bool)
     * 
     */
    @Import(name="updateOnly")
    private @Nullable Output<Boolean> updateOnly;

    /**
     * @return Skip idempotent deployment of control and etcd plane. Default `false` (bool)
     * 
     */
    public Optional<Output<Boolean>> updateOnly() {
        return Optional.ofNullable(this.updateOnly);
    }

    /**
     * RKE k8s cluster upgrade strategy (list maxitems:1)
     * 
     */
    @Import(name="upgradeStrategy")
    private @Nullable Output<ClusterUpgradeStrategyArgs> upgradeStrategy;

    /**
     * @return RKE k8s cluster upgrade strategy (list maxitems:1)
     * 
     */
    public Optional<Output<ClusterUpgradeStrategyArgs>> upgradeStrategy() {
        return Optional.ofNullable(this.upgradeStrategy);
    }

    /**
     * (Computed) RKE k8s cluster worker nodes (list)
     * 
     */
    @Import(name="workerHosts")
    private @Nullable Output<List<ClusterWorkerHostArgs>> workerHosts;

    /**
     * @return (Computed) RKE k8s cluster worker nodes (list)
     * 
     */
    public Optional<Output<List<ClusterWorkerHostArgs>>> workerHosts() {
        return Optional.ofNullable(this.workerHosts);
    }

    private ClusterState() {}

    private ClusterState(ClusterState $) {
        this.addonJobTimeout = $.addonJobTimeout;
        this.addons = $.addons;
        this.addonsIncludes = $.addonsIncludes;
        this.apiServerUrl = $.apiServerUrl;
        this.authentication = $.authentication;
        this.authorization = $.authorization;
        this.bastionHost = $.bastionHost;
        this.caCrt = $.caCrt;
        this.certDir = $.certDir;
        this.certificates = $.certificates;
        this.clientCert = $.clientCert;
        this.clientKey = $.clientKey;
        this.cloudProvider = $.cloudProvider;
        this.clusterCidr = $.clusterCidr;
        this.clusterDnsServer = $.clusterDnsServer;
        this.clusterDomain = $.clusterDomain;
        this.clusterName = $.clusterName;
        this.clusterYaml = $.clusterYaml;
        this.controlPlaneHosts = $.controlPlaneHosts;
        this.customCerts = $.customCerts;
        this.delayOnCreation = $.delayOnCreation;
        this.dind = $.dind;
        this.dindDnsServer = $.dindDnsServer;
        this.dindStorageDriver = $.dindStorageDriver;
        this.disablePortCheck = $.disablePortCheck;
        this.dns = $.dns;
        this.enableCriDockerd = $.enableCriDockerd;
        this.etcdHosts = $.etcdHosts;
        this.ignoreDockerVersion = $.ignoreDockerVersion;
        this.inactiveHosts = $.inactiveHosts;
        this.ingress = $.ingress;
        this.internalKubeConfigYaml = $.internalKubeConfigYaml;
        this.kubeAdminUser = $.kubeAdminUser;
        this.kubeConfigYaml = $.kubeConfigYaml;
        this.kubernetesVersion = $.kubernetesVersion;
        this.monitoring = $.monitoring;
        this.network = $.network;
        this.nodes = $.nodes;
        this.nodesConfs = $.nodesConfs;
        this.prefixPath = $.prefixPath;
        this.privateRegistries = $.privateRegistries;
        this.restore = $.restore;
        this.rkeClusterYaml = $.rkeClusterYaml;
        this.rkeState = $.rkeState;
        this.rotateCertificates = $.rotateCertificates;
        this.runningSystemImages = $.runningSystemImages;
        this.services = $.services;
        this.servicesEtcdDeprecated = $.servicesEtcdDeprecated;
        this.servicesKubeApiDeprecated = $.servicesKubeApiDeprecated;
        this.servicesKubeControllerDeprecated = $.servicesKubeControllerDeprecated;
        this.servicesKubeProxyDeprecated = $.servicesKubeProxyDeprecated;
        this.servicesKubeSchedulerDeprecated = $.servicesKubeSchedulerDeprecated;
        this.servicesKubeletDeprecated = $.servicesKubeletDeprecated;
        this.sshAgentAuth = $.sshAgentAuth;
        this.sshCertPath = $.sshCertPath;
        this.sshKeyPath = $.sshKeyPath;
        this.systemImages = $.systemImages;
        this.updateOnly = $.updateOnly;
        this.upgradeStrategy = $.upgradeStrategy;
        this.workerHosts = $.workerHosts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterState $;

        public Builder() {
            $ = new ClusterState();
        }

        public Builder(ClusterState defaults) {
            $ = new ClusterState(Objects.requireNonNull(defaults));
        }

        /**
         * @param addonJobTimeout RKE k8s cluster addon deployment timeout in seconds for status check (int)
         * 
         * @return builder
         * 
         */
        public Builder addonJobTimeout(@Nullable Output<Integer> addonJobTimeout) {
            $.addonJobTimeout = addonJobTimeout;
            return this;
        }

        /**
         * @param addonJobTimeout RKE k8s cluster addon deployment timeout in seconds for status check (int)
         * 
         * @return builder
         * 
         */
        public Builder addonJobTimeout(Integer addonJobTimeout) {
            return addonJobTimeout(Output.of(addonJobTimeout));
        }

        /**
         * @param addons RKE k8s cluster user addons YAML manifest to be deployed (string)
         * 
         * @return builder
         * 
         */
        public Builder addons(@Nullable Output<String> addons) {
            $.addons = addons;
            return this;
        }

        /**
         * @param addons RKE k8s cluster user addons YAML manifest to be deployed (string)
         * 
         * @return builder
         * 
         */
        public Builder addons(String addons) {
            return addons(Output.of(addons));
        }

        /**
         * @param addonsIncludes RKE k8s cluster user addons YAML manifest urls or paths to be deployed (list)
         * 
         * @return builder
         * 
         */
        public Builder addonsIncludes(@Nullable Output<List<String>> addonsIncludes) {
            $.addonsIncludes = addonsIncludes;
            return this;
        }

        /**
         * @param addonsIncludes RKE k8s cluster user addons YAML manifest urls or paths to be deployed (list)
         * 
         * @return builder
         * 
         */
        public Builder addonsIncludes(List<String> addonsIncludes) {
            return addonsIncludes(Output.of(addonsIncludes));
        }

        /**
         * @param addonsIncludes RKE k8s cluster user addons YAML manifest urls or paths to be deployed (list)
         * 
         * @return builder
         * 
         */
        public Builder addonsIncludes(String... addonsIncludes) {
            return addonsIncludes(List.of(addonsIncludes));
        }

        /**
         * @param apiServerUrl (Computed) RKE k8s cluster api server url (string)
         * 
         * @return builder
         * 
         */
        public Builder apiServerUrl(@Nullable Output<String> apiServerUrl) {
            $.apiServerUrl = apiServerUrl;
            return this;
        }

        /**
         * @param apiServerUrl (Computed) RKE k8s cluster api server url (string)
         * 
         * @return builder
         * 
         */
        public Builder apiServerUrl(String apiServerUrl) {
            return apiServerUrl(Output.of(apiServerUrl));
        }

        /**
         * @param authentication RKE k8s cluster authentication configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder authentication(@Nullable Output<ClusterAuthenticationArgs> authentication) {
            $.authentication = authentication;
            return this;
        }

        /**
         * @param authentication RKE k8s cluster authentication configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder authentication(ClusterAuthenticationArgs authentication) {
            return authentication(Output.of(authentication));
        }

        /**
         * @param authorization RKE k8s cluster authorization mode configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder authorization(@Nullable Output<ClusterAuthorizationArgs> authorization) {
            $.authorization = authorization;
            return this;
        }

        /**
         * @param authorization RKE k8s cluster authorization mode configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder authorization(ClusterAuthorizationArgs authorization) {
            return authorization(Output.of(authorization));
        }

        /**
         * @param bastionHost RKE k8s cluster bastion Host configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder bastionHost(@Nullable Output<ClusterBastionHostArgs> bastionHost) {
            $.bastionHost = bastionHost;
            return this;
        }

        /**
         * @param bastionHost RKE k8s cluster bastion Host configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder bastionHost(ClusterBastionHostArgs bastionHost) {
            return bastionHost(Output.of(bastionHost));
        }

        /**
         * @param caCrt (Computed/Sensitive) RKE k8s cluster CA certificate (string)
         * 
         * @return builder
         * 
         */
        public Builder caCrt(@Nullable Output<String> caCrt) {
            $.caCrt = caCrt;
            return this;
        }

        /**
         * @param caCrt (Computed/Sensitive) RKE k8s cluster CA certificate (string)
         * 
         * @return builder
         * 
         */
        public Builder caCrt(String caCrt) {
            return caCrt(Output.of(caCrt));
        }

        /**
         * @param certDir Specify a certificate dir path (string)
         * 
         * @return builder
         * 
         */
        public Builder certDir(@Nullable Output<String> certDir) {
            $.certDir = certDir;
            return this;
        }

        /**
         * @param certDir Specify a certificate dir path (string)
         * 
         * @return builder
         * 
         */
        public Builder certDir(String certDir) {
            return certDir(Output.of(certDir));
        }

        /**
         * @param certificates (Computed/Sensitive) RKE k8s cluster certificates (string)
         * 
         * @return builder
         * 
         */
        public Builder certificates(@Nullable Output<List<ClusterCertificateArgs>> certificates) {
            $.certificates = certificates;
            return this;
        }

        /**
         * @param certificates (Computed/Sensitive) RKE k8s cluster certificates (string)
         * 
         * @return builder
         * 
         */
        public Builder certificates(List<ClusterCertificateArgs> certificates) {
            return certificates(Output.of(certificates));
        }

        /**
         * @param certificates (Computed/Sensitive) RKE k8s cluster certificates (string)
         * 
         * @return builder
         * 
         */
        public Builder certificates(ClusterCertificateArgs... certificates) {
            return certificates(List.of(certificates));
        }

        /**
         * @param clientCert (Computed/Sensitive) RKE k8s cluster client certificate (string)
         * 
         * @return builder
         * 
         */
        public Builder clientCert(@Nullable Output<String> clientCert) {
            $.clientCert = clientCert;
            return this;
        }

        /**
         * @param clientCert (Computed/Sensitive) RKE k8s cluster client certificate (string)
         * 
         * @return builder
         * 
         */
        public Builder clientCert(String clientCert) {
            return clientCert(Output.of(clientCert));
        }

        /**
         * @param clientKey (Computed/Sensitive) RKE k8s cluster client key (string)
         * 
         * @return builder
         * 
         */
        public Builder clientKey(@Nullable Output<String> clientKey) {
            $.clientKey = clientKey;
            return this;
        }

        /**
         * @param clientKey (Computed/Sensitive) RKE k8s cluster client key (string)
         * 
         * @return builder
         * 
         */
        public Builder clientKey(String clientKey) {
            return clientKey(Output.of(clientKey));
        }

        /**
         * @param cloudProvider RKE k8s cluster cloud provider configuration [rke-cloud-providers](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/) (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder cloudProvider(@Nullable Output<ClusterCloudProviderArgs> cloudProvider) {
            $.cloudProvider = cloudProvider;
            return this;
        }

        /**
         * @param cloudProvider RKE k8s cluster cloud provider configuration [rke-cloud-providers](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/) (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder cloudProvider(ClusterCloudProviderArgs cloudProvider) {
            return cloudProvider(Output.of(cloudProvider));
        }

        /**
         * @param clusterCidr Cluster CIDR option for kube controller service (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterCidr(@Nullable Output<String> clusterCidr) {
            $.clusterCidr = clusterCidr;
            return this;
        }

        /**
         * @param clusterCidr Cluster CIDR option for kube controller service (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterCidr(String clusterCidr) {
            return clusterCidr(Output.of(clusterCidr));
        }

        /**
         * @param clusterDnsServer Cluster DNS Server option for kubelet service (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterDnsServer(@Nullable Output<String> clusterDnsServer) {
            $.clusterDnsServer = clusterDnsServer;
            return this;
        }

        /**
         * @param clusterDnsServer Cluster DNS Server option for kubelet service (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterDnsServer(String clusterDnsServer) {
            return clusterDnsServer(Output.of(clusterDnsServer));
        }

        /**
         * @param clusterDomain Cluster Domain option for kubelet service. Default `cluster.local` (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterDomain(@Nullable Output<String> clusterDomain) {
            $.clusterDomain = clusterDomain;
            return this;
        }

        /**
         * @param clusterDomain Cluster Domain option for kubelet service. Default `cluster.local` (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterDomain(String clusterDomain) {
            return clusterDomain(Output.of(clusterDomain));
        }

        /**
         * @param clusterName RKE k8s cluster name used in the kube config (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterName(@Nullable Output<String> clusterName) {
            $.clusterName = clusterName;
            return this;
        }

        /**
         * @param clusterName RKE k8s cluster name used in the kube config (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterName(String clusterName) {
            return clusterName(Output.of(clusterName));
        }

        /**
         * @param clusterYaml RKE k8s cluster config yaml encoded. Provider arguments take precedence over this one (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterYaml(@Nullable Output<String> clusterYaml) {
            $.clusterYaml = clusterYaml;
            return this;
        }

        /**
         * @param clusterYaml RKE k8s cluster config yaml encoded. Provider arguments take precedence over this one (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterYaml(String clusterYaml) {
            return clusterYaml(Output.of(clusterYaml));
        }

        /**
         * @param controlPlaneHosts (Computed) RKE k8s cluster control plane nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder controlPlaneHosts(@Nullable Output<List<ClusterControlPlaneHostArgs>> controlPlaneHosts) {
            $.controlPlaneHosts = controlPlaneHosts;
            return this;
        }

        /**
         * @param controlPlaneHosts (Computed) RKE k8s cluster control plane nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder controlPlaneHosts(List<ClusterControlPlaneHostArgs> controlPlaneHosts) {
            return controlPlaneHosts(Output.of(controlPlaneHosts));
        }

        /**
         * @param controlPlaneHosts (Computed) RKE k8s cluster control plane nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder controlPlaneHosts(ClusterControlPlaneHostArgs... controlPlaneHosts) {
            return controlPlaneHosts(List.of(controlPlaneHosts));
        }

        /**
         * @param customCerts Use custom certificates from a cert dir (string)
         * 
         * @return builder
         * 
         */
        public Builder customCerts(@Nullable Output<Boolean> customCerts) {
            $.customCerts = customCerts;
            return this;
        }

        /**
         * @param customCerts Use custom certificates from a cert dir (string)
         * 
         * @return builder
         * 
         */
        public Builder customCerts(Boolean customCerts) {
            return customCerts(Output.of(customCerts));
        }

        /**
         * @param delayOnCreation RKE k8s cluster delay on creation (int)
         * 
         * @return builder
         * 
         */
        public Builder delayOnCreation(@Nullable Output<Integer> delayOnCreation) {
            $.delayOnCreation = delayOnCreation;
            return this;
        }

        /**
         * @param delayOnCreation RKE k8s cluster delay on creation (int)
         * 
         * @return builder
         * 
         */
        public Builder delayOnCreation(Integer delayOnCreation) {
            return delayOnCreation(Output.of(delayOnCreation));
        }

        /**
         * @param dind Deploy RKE cluster on a dind environment. Default: `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder dind(@Nullable Output<Boolean> dind) {
            $.dind = dind;
            return this;
        }

        /**
         * @param dind Deploy RKE cluster on a dind environment. Default: `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder dind(Boolean dind) {
            return dind(Output.of(dind));
        }

        /**
         * @param dindDnsServer DinD RKE cluster dns (string)
         * 
         * @return builder
         * 
         */
        public Builder dindDnsServer(@Nullable Output<String> dindDnsServer) {
            $.dindDnsServer = dindDnsServer;
            return this;
        }

        /**
         * @param dindDnsServer DinD RKE cluster dns (string)
         * 
         * @return builder
         * 
         */
        public Builder dindDnsServer(String dindDnsServer) {
            return dindDnsServer(Output.of(dindDnsServer));
        }

        /**
         * @param dindStorageDriver DinD RKE cluster storage driver (string)
         * 
         * @return builder
         * 
         */
        public Builder dindStorageDriver(@Nullable Output<String> dindStorageDriver) {
            $.dindStorageDriver = dindStorageDriver;
            return this;
        }

        /**
         * @param dindStorageDriver DinD RKE cluster storage driver (string)
         * 
         * @return builder
         * 
         */
        public Builder dindStorageDriver(String dindStorageDriver) {
            return dindStorageDriver(Output.of(dindStorageDriver));
        }

        /**
         * @param disablePortCheck Enable/Disable RKE k8s cluster port checking. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder disablePortCheck(@Nullable Output<Boolean> disablePortCheck) {
            $.disablePortCheck = disablePortCheck;
            return this;
        }

        /**
         * @param disablePortCheck Enable/Disable RKE k8s cluster port checking. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder disablePortCheck(Boolean disablePortCheck) {
            return disablePortCheck(Output.of(disablePortCheck));
        }

        /**
         * @param dns RKE k8s cluster DNS Config (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder dns(@Nullable Output<ClusterDnsArgs> dns) {
            $.dns = dns;
            return this;
        }

        /**
         * @param dns RKE k8s cluster DNS Config (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder dns(ClusterDnsArgs dns) {
            return dns(Output.of(dns));
        }

        /**
         * @param enableCriDockerd Enable/Disable CRI dockerd for kubelet; set it to true starting from Kubernetes version 1.24 or later. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder enableCriDockerd(@Nullable Output<Boolean> enableCriDockerd) {
            $.enableCriDockerd = enableCriDockerd;
            return this;
        }

        /**
         * @param enableCriDockerd Enable/Disable CRI dockerd for kubelet; set it to true starting from Kubernetes version 1.24 or later. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder enableCriDockerd(Boolean enableCriDockerd) {
            return enableCriDockerd(Output.of(enableCriDockerd));
        }

        /**
         * @param etcdHosts (Computed) RKE k8s cluster etcd nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder etcdHosts(@Nullable Output<List<ClusterEtcdHostArgs>> etcdHosts) {
            $.etcdHosts = etcdHosts;
            return this;
        }

        /**
         * @param etcdHosts (Computed) RKE k8s cluster etcd nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder etcdHosts(List<ClusterEtcdHostArgs> etcdHosts) {
            return etcdHosts(Output.of(etcdHosts));
        }

        /**
         * @param etcdHosts (Computed) RKE k8s cluster etcd nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder etcdHosts(ClusterEtcdHostArgs... etcdHosts) {
            return etcdHosts(List.of(etcdHosts));
        }

        /**
         * @param ignoreDockerVersion Enable/Disable RKE k8s cluster strict docker version checking. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder ignoreDockerVersion(@Nullable Output<Boolean> ignoreDockerVersion) {
            $.ignoreDockerVersion = ignoreDockerVersion;
            return this;
        }

        /**
         * @param ignoreDockerVersion Enable/Disable RKE k8s cluster strict docker version checking. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder ignoreDockerVersion(Boolean ignoreDockerVersion) {
            return ignoreDockerVersion(Output.of(ignoreDockerVersion));
        }

        /**
         * @param inactiveHosts (Computed) RKE k8s cluster inactive nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder inactiveHosts(@Nullable Output<List<ClusterInactiveHostArgs>> inactiveHosts) {
            $.inactiveHosts = inactiveHosts;
            return this;
        }

        /**
         * @param inactiveHosts (Computed) RKE k8s cluster inactive nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder inactiveHosts(List<ClusterInactiveHostArgs> inactiveHosts) {
            return inactiveHosts(Output.of(inactiveHosts));
        }

        /**
         * @param inactiveHosts (Computed) RKE k8s cluster inactive nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder inactiveHosts(ClusterInactiveHostArgs... inactiveHosts) {
            return inactiveHosts(List.of(inactiveHosts));
        }

        /**
         * @param ingress RKE k8s cluster ingress controller configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder ingress(@Nullable Output<ClusterIngressArgs> ingress) {
            $.ingress = ingress;
            return this;
        }

        /**
         * @param ingress RKE k8s cluster ingress controller configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder ingress(ClusterIngressArgs ingress) {
            return ingress(Output.of(ingress));
        }

        /**
         * @param internalKubeConfigYaml (Computed/Sensitive) RKE k8s cluster internal kube config yaml (string)
         * 
         * @return builder
         * 
         * @deprecated
         * Use kube_config_yaml instead
         * 
         */
        @Deprecated /* Use kube_config_yaml instead */
        public Builder internalKubeConfigYaml(@Nullable Output<String> internalKubeConfigYaml) {
            $.internalKubeConfigYaml = internalKubeConfigYaml;
            return this;
        }

        /**
         * @param internalKubeConfigYaml (Computed/Sensitive) RKE k8s cluster internal kube config yaml (string)
         * 
         * @return builder
         * 
         * @deprecated
         * Use kube_config_yaml instead
         * 
         */
        @Deprecated /* Use kube_config_yaml instead */
        public Builder internalKubeConfigYaml(String internalKubeConfigYaml) {
            return internalKubeConfigYaml(Output.of(internalKubeConfigYaml));
        }

        /**
         * @param kubeAdminUser (Computed) RKE k8s cluster admin user (string)
         * 
         * @return builder
         * 
         */
        public Builder kubeAdminUser(@Nullable Output<String> kubeAdminUser) {
            $.kubeAdminUser = kubeAdminUser;
            return this;
        }

        /**
         * @param kubeAdminUser (Computed) RKE k8s cluster admin user (string)
         * 
         * @return builder
         * 
         */
        public Builder kubeAdminUser(String kubeAdminUser) {
            return kubeAdminUser(Output.of(kubeAdminUser));
        }

        /**
         * @param kubeConfigYaml (Computed/Sensitive) RKE k8s cluster kube config yaml (string)
         * 
         * @return builder
         * 
         */
        public Builder kubeConfigYaml(@Nullable Output<String> kubeConfigYaml) {
            $.kubeConfigYaml = kubeConfigYaml;
            return this;
        }

        /**
         * @param kubeConfigYaml (Computed/Sensitive) RKE k8s cluster kube config yaml (string)
         * 
         * @return builder
         * 
         */
        public Builder kubeConfigYaml(String kubeConfigYaml) {
            return kubeConfigYaml(Output.of(kubeConfigYaml));
        }

        /**
         * @param kubernetesVersion K8s version to deploy. If kubernetes image is specified, image version takes precedence. Default: `rke default` (string)
         * 
         * @return builder
         * 
         */
        public Builder kubernetesVersion(@Nullable Output<String> kubernetesVersion) {
            $.kubernetesVersion = kubernetesVersion;
            return this;
        }

        /**
         * @param kubernetesVersion K8s version to deploy. If kubernetes image is specified, image version takes precedence. Default: `rke default` (string)
         * 
         * @return builder
         * 
         */
        public Builder kubernetesVersion(String kubernetesVersion) {
            return kubernetesVersion(Output.of(kubernetesVersion));
        }

        /**
         * @param monitoring RKE k8s cluster monitoring Config (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder monitoring(@Nullable Output<ClusterMonitoringArgs> monitoring) {
            $.monitoring = monitoring;
            return this;
        }

        /**
         * @param monitoring RKE k8s cluster monitoring Config (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder monitoring(ClusterMonitoringArgs monitoring) {
            return monitoring(Output.of(monitoring));
        }

        /**
         * @param network RKE k8s cluster network configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder network(@Nullable Output<ClusterNetworkArgs> network) {
            $.network = network;
            return this;
        }

        /**
         * @param network RKE k8s cluster network configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder network(ClusterNetworkArgs network) {
            return network(Output.of(network));
        }

        /**
         * @param nodes RKE k8s cluster nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder nodes(@Nullable Output<List<ClusterNodeArgs>> nodes) {
            $.nodes = nodes;
            return this;
        }

        /**
         * @param nodes RKE k8s cluster nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder nodes(List<ClusterNodeArgs> nodes) {
            return nodes(Output.of(nodes));
        }

        /**
         * @param nodes RKE k8s cluster nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder nodes(ClusterNodeArgs... nodes) {
            return nodes(List.of(nodes));
        }

        /**
         * @return builder
         * 
         * @deprecated
         * Use cluster_yaml instead
         * 
         */
        @Deprecated /* Use cluster_yaml instead */
        public Builder nodesConfs(@Nullable Output<List<String>> nodesConfs) {
            $.nodesConfs = nodesConfs;
            return this;
        }

        /**
         * @return builder
         * 
         * @deprecated
         * Use cluster_yaml instead
         * 
         */
        @Deprecated /* Use cluster_yaml instead */
        public Builder nodesConfs(List<String> nodesConfs) {
            return nodesConfs(Output.of(nodesConfs));
        }

        /**
         * @return builder
         * 
         * @deprecated
         * Use cluster_yaml instead
         * 
         */
        @Deprecated /* Use cluster_yaml instead */
        public Builder nodesConfs(String... nodesConfs) {
            return nodesConfs(List.of(nodesConfs));
        }

        /**
         * @param prefixPath RKE k8s directory path (string)
         * 
         * @return builder
         * 
         */
        public Builder prefixPath(@Nullable Output<String> prefixPath) {
            $.prefixPath = prefixPath;
            return this;
        }

        /**
         * @param prefixPath RKE k8s directory path (string)
         * 
         * @return builder
         * 
         */
        public Builder prefixPath(String prefixPath) {
            return prefixPath(Output.of(prefixPath));
        }

        /**
         * @param privateRegistries RKE k8s cluster private docker registries (list)
         * 
         * @return builder
         * 
         */
        public Builder privateRegistries(@Nullable Output<List<ClusterPrivateRegistryArgs>> privateRegistries) {
            $.privateRegistries = privateRegistries;
            return this;
        }

        /**
         * @param privateRegistries RKE k8s cluster private docker registries (list)
         * 
         * @return builder
         * 
         */
        public Builder privateRegistries(List<ClusterPrivateRegistryArgs> privateRegistries) {
            return privateRegistries(Output.of(privateRegistries));
        }

        /**
         * @param privateRegistries RKE k8s cluster private docker registries (list)
         * 
         * @return builder
         * 
         */
        public Builder privateRegistries(ClusterPrivateRegistryArgs... privateRegistries) {
            return privateRegistries(List.of(privateRegistries));
        }

        /**
         * @param restore RKE k8s cluster restore configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder restore(@Nullable Output<ClusterRestoreArgs> restore) {
            $.restore = restore;
            return this;
        }

        /**
         * @param restore RKE k8s cluster restore configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder restore(ClusterRestoreArgs restore) {
            return restore(Output.of(restore));
        }

        /**
         * @param rkeClusterYaml (Computed/Sensitive) RKE k8s cluster config yaml (string)
         * 
         * @return builder
         * 
         */
        public Builder rkeClusterYaml(@Nullable Output<String> rkeClusterYaml) {
            $.rkeClusterYaml = rkeClusterYaml;
            return this;
        }

        /**
         * @param rkeClusterYaml (Computed/Sensitive) RKE k8s cluster config yaml (string)
         * 
         * @return builder
         * 
         */
        public Builder rkeClusterYaml(String rkeClusterYaml) {
            return rkeClusterYaml(Output.of(rkeClusterYaml));
        }

        /**
         * @param rkeState (Computed/Sensitive) RKE k8s cluster state (string)
         * 
         * @return builder
         * 
         */
        public Builder rkeState(@Nullable Output<String> rkeState) {
            $.rkeState = rkeState;
            return this;
        }

        /**
         * @param rkeState (Computed/Sensitive) RKE k8s cluster state (string)
         * 
         * @return builder
         * 
         */
        public Builder rkeState(String rkeState) {
            return rkeState(Output.of(rkeState));
        }

        /**
         * @param rotateCertificates RKE k8s cluster rotate certificates configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder rotateCertificates(@Nullable Output<ClusterRotateCertificatesArgs> rotateCertificates) {
            $.rotateCertificates = rotateCertificates;
            return this;
        }

        /**
         * @param rotateCertificates RKE k8s cluster rotate certificates configuration (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder rotateCertificates(ClusterRotateCertificatesArgs rotateCertificates) {
            return rotateCertificates(Output.of(rotateCertificates));
        }

        /**
         * @param runningSystemImages (Computed) RKE k8s cluster running system images list (list)
         * 
         * @return builder
         * 
         */
        public Builder runningSystemImages(@Nullable Output<List<ClusterRunningSystemImageArgs>> runningSystemImages) {
            $.runningSystemImages = runningSystemImages;
            return this;
        }

        /**
         * @param runningSystemImages (Computed) RKE k8s cluster running system images list (list)
         * 
         * @return builder
         * 
         */
        public Builder runningSystemImages(List<ClusterRunningSystemImageArgs> runningSystemImages) {
            return runningSystemImages(Output.of(runningSystemImages));
        }

        /**
         * @param runningSystemImages (Computed) RKE k8s cluster running system images list (list)
         * 
         * @return builder
         * 
         */
        public Builder runningSystemImages(ClusterRunningSystemImageArgs... runningSystemImages) {
            return runningSystemImages(List.of(runningSystemImages));
        }

        /**
         * @param services RKE k8s cluster services (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder services(@Nullable Output<ClusterServicesArgs> services) {
            $.services = services;
            return this;
        }

        /**
         * @param services RKE k8s cluster services (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder services(ClusterServicesArgs services) {
            return services(Output.of(services));
        }

        /**
         * @param servicesEtcdDeprecated Use services.etcd instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.etcd instead
         * 
         */
        @Deprecated /* Use services.etcd instead */
        public Builder servicesEtcdDeprecated(@Nullable Output<ClusterServicesEtcdDeprecatedArgs> servicesEtcdDeprecated) {
            $.servicesEtcdDeprecated = servicesEtcdDeprecated;
            return this;
        }

        /**
         * @param servicesEtcdDeprecated Use services.etcd instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.etcd instead
         * 
         */
        @Deprecated /* Use services.etcd instead */
        public Builder servicesEtcdDeprecated(ClusterServicesEtcdDeprecatedArgs servicesEtcdDeprecated) {
            return servicesEtcdDeprecated(Output.of(servicesEtcdDeprecated));
        }

        /**
         * @param servicesKubeApiDeprecated Use services.kube_api instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kube_api instead
         * 
         */
        @Deprecated /* Use services.kube_api instead */
        public Builder servicesKubeApiDeprecated(@Nullable Output<ClusterServicesKubeApiDeprecatedArgs> servicesKubeApiDeprecated) {
            $.servicesKubeApiDeprecated = servicesKubeApiDeprecated;
            return this;
        }

        /**
         * @param servicesKubeApiDeprecated Use services.kube_api instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kube_api instead
         * 
         */
        @Deprecated /* Use services.kube_api instead */
        public Builder servicesKubeApiDeprecated(ClusterServicesKubeApiDeprecatedArgs servicesKubeApiDeprecated) {
            return servicesKubeApiDeprecated(Output.of(servicesKubeApiDeprecated));
        }

        /**
         * @param servicesKubeControllerDeprecated Use services.kube_controller instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kube_controller instead
         * 
         */
        @Deprecated /* Use services.kube_controller instead */
        public Builder servicesKubeControllerDeprecated(@Nullable Output<ClusterServicesKubeControllerDeprecatedArgs> servicesKubeControllerDeprecated) {
            $.servicesKubeControllerDeprecated = servicesKubeControllerDeprecated;
            return this;
        }

        /**
         * @param servicesKubeControllerDeprecated Use services.kube_controller instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kube_controller instead
         * 
         */
        @Deprecated /* Use services.kube_controller instead */
        public Builder servicesKubeControllerDeprecated(ClusterServicesKubeControllerDeprecatedArgs servicesKubeControllerDeprecated) {
            return servicesKubeControllerDeprecated(Output.of(servicesKubeControllerDeprecated));
        }

        /**
         * @param servicesKubeProxyDeprecated Use services.kubeproxy instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kubeproxy instead
         * 
         */
        @Deprecated /* Use services.kubeproxy instead */
        public Builder servicesKubeProxyDeprecated(@Nullable Output<ClusterServicesKubeProxyDeprecatedArgs> servicesKubeProxyDeprecated) {
            $.servicesKubeProxyDeprecated = servicesKubeProxyDeprecated;
            return this;
        }

        /**
         * @param servicesKubeProxyDeprecated Use services.kubeproxy instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kubeproxy instead
         * 
         */
        @Deprecated /* Use services.kubeproxy instead */
        public Builder servicesKubeProxyDeprecated(ClusterServicesKubeProxyDeprecatedArgs servicesKubeProxyDeprecated) {
            return servicesKubeProxyDeprecated(Output.of(servicesKubeProxyDeprecated));
        }

        /**
         * @param servicesKubeSchedulerDeprecated Use services.scheduler instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.scheduler instead
         * 
         */
        @Deprecated /* Use services.scheduler instead */
        public Builder servicesKubeSchedulerDeprecated(@Nullable Output<ClusterServicesKubeSchedulerDeprecatedArgs> servicesKubeSchedulerDeprecated) {
            $.servicesKubeSchedulerDeprecated = servicesKubeSchedulerDeprecated;
            return this;
        }

        /**
         * @param servicesKubeSchedulerDeprecated Use services.scheduler instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.scheduler instead
         * 
         */
        @Deprecated /* Use services.scheduler instead */
        public Builder servicesKubeSchedulerDeprecated(ClusterServicesKubeSchedulerDeprecatedArgs servicesKubeSchedulerDeprecated) {
            return servicesKubeSchedulerDeprecated(Output.of(servicesKubeSchedulerDeprecated));
        }

        /**
         * @param servicesKubeletDeprecated Use services.kubelet instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kubelet instead
         * 
         */
        @Deprecated /* Use services.kubelet instead */
        public Builder servicesKubeletDeprecated(@Nullable Output<ClusterServicesKubeletDeprecatedArgs> servicesKubeletDeprecated) {
            $.servicesKubeletDeprecated = servicesKubeletDeprecated;
            return this;
        }

        /**
         * @param servicesKubeletDeprecated Use services.kubelet instead (list maxitems:1)
         * 
         * @return builder
         * 
         * @deprecated
         * Use services.kubelet instead
         * 
         */
        @Deprecated /* Use services.kubelet instead */
        public Builder servicesKubeletDeprecated(ClusterServicesKubeletDeprecatedArgs servicesKubeletDeprecated) {
            return servicesKubeletDeprecated(Output.of(servicesKubeletDeprecated));
        }

        /**
         * @param sshAgentAuth SSH Agent Auth enable (bool)
         * 
         * @return builder
         * 
         */
        public Builder sshAgentAuth(@Nullable Output<Boolean> sshAgentAuth) {
            $.sshAgentAuth = sshAgentAuth;
            return this;
        }

        /**
         * @param sshAgentAuth SSH Agent Auth enable (bool)
         * 
         * @return builder
         * 
         */
        public Builder sshAgentAuth(Boolean sshAgentAuth) {
            return sshAgentAuth(Output.of(sshAgentAuth));
        }

        /**
         * @param sshCertPath SSH Certificate Path (string)
         * 
         * @return builder
         * 
         */
        public Builder sshCertPath(@Nullable Output<String> sshCertPath) {
            $.sshCertPath = sshCertPath;
            return this;
        }

        /**
         * @param sshCertPath SSH Certificate Path (string)
         * 
         * @return builder
         * 
         */
        public Builder sshCertPath(String sshCertPath) {
            return sshCertPath(Output.of(sshCertPath));
        }

        /**
         * @param sshKeyPath SSH Private Key Path (string)
         * 
         * @return builder
         * 
         */
        public Builder sshKeyPath(@Nullable Output<String> sshKeyPath) {
            $.sshKeyPath = sshKeyPath;
            return this;
        }

        /**
         * @param sshKeyPath SSH Private Key Path (string)
         * 
         * @return builder
         * 
         */
        public Builder sshKeyPath(String sshKeyPath) {
            return sshKeyPath(Output.of(sshKeyPath));
        }

        /**
         * @param systemImages RKE k8s cluster system images list (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder systemImages(@Nullable Output<ClusterSystemImagesArgs> systemImages) {
            $.systemImages = systemImages;
            return this;
        }

        /**
         * @param systemImages RKE k8s cluster system images list (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder systemImages(ClusterSystemImagesArgs systemImages) {
            return systemImages(Output.of(systemImages));
        }

        /**
         * @param updateOnly Skip idempotent deployment of control and etcd plane. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder updateOnly(@Nullable Output<Boolean> updateOnly) {
            $.updateOnly = updateOnly;
            return this;
        }

        /**
         * @param updateOnly Skip idempotent deployment of control and etcd plane. Default `false` (bool)
         * 
         * @return builder
         * 
         */
        public Builder updateOnly(Boolean updateOnly) {
            return updateOnly(Output.of(updateOnly));
        }

        /**
         * @param upgradeStrategy RKE k8s cluster upgrade strategy (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder upgradeStrategy(@Nullable Output<ClusterUpgradeStrategyArgs> upgradeStrategy) {
            $.upgradeStrategy = upgradeStrategy;
            return this;
        }

        /**
         * @param upgradeStrategy RKE k8s cluster upgrade strategy (list maxitems:1)
         * 
         * @return builder
         * 
         */
        public Builder upgradeStrategy(ClusterUpgradeStrategyArgs upgradeStrategy) {
            return upgradeStrategy(Output.of(upgradeStrategy));
        }

        /**
         * @param workerHosts (Computed) RKE k8s cluster worker nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder workerHosts(@Nullable Output<List<ClusterWorkerHostArgs>> workerHosts) {
            $.workerHosts = workerHosts;
            return this;
        }

        /**
         * @param workerHosts (Computed) RKE k8s cluster worker nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder workerHosts(List<ClusterWorkerHostArgs> workerHosts) {
            return workerHosts(Output.of(workerHosts));
        }

        /**
         * @param workerHosts (Computed) RKE k8s cluster worker nodes (list)
         * 
         * @return builder
         * 
         */
        public Builder workerHosts(ClusterWorkerHostArgs... workerHosts) {
            return workerHosts(List.of(workerHosts));
        }

        public ClusterState build() {
            return $;
        }
    }

}
