// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.rke.inputs.ClusterServicesKubeApiAuditLogConfigurationArgs;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterServicesKubeApiAuditLogArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterServicesKubeApiAuditLogArgs Empty = new ClusterServicesKubeApiAuditLogArgs();

    @Import(name="configuration")
    private @Nullable Output<ClusterServicesKubeApiAuditLogConfigurationArgs> configuration;

    public Optional<Output<ClusterServicesKubeApiAuditLogConfigurationArgs>> configuration() {
        return Optional.ofNullable(this.configuration);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    private ClusterServicesKubeApiAuditLogArgs() {}

    private ClusterServicesKubeApiAuditLogArgs(ClusterServicesKubeApiAuditLogArgs $) {
        this.configuration = $.configuration;
        this.enabled = $.enabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterServicesKubeApiAuditLogArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterServicesKubeApiAuditLogArgs $;

        public Builder() {
            $ = new ClusterServicesKubeApiAuditLogArgs();
        }

        public Builder(ClusterServicesKubeApiAuditLogArgs defaults) {
            $ = new ClusterServicesKubeApiAuditLogArgs(Objects.requireNonNull(defaults));
        }

        public Builder configuration(@Nullable Output<ClusterServicesKubeApiAuditLogConfigurationArgs> configuration) {
            $.configuration = configuration;
            return this;
        }

        public Builder configuration(ClusterServicesKubeApiAuditLogConfigurationArgs configuration) {
            return configuration(Output.of(configuration));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public ClusterServicesKubeApiAuditLogArgs build() {
            return $;
        }
    }

}
