// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterInactiveHostArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterInactiveHostArgs Empty = new ClusterInactiveHostArgs();

    /**
     * Address of Bastion Host (string)
     * 
     */
    @Import(name="address")
    private @Nullable Output<String> address;

    /**
     * @return Address of Bastion Host (string)
     * 
     */
    public Optional<Output<String>> address() {
        return Optional.ofNullable(this.address);
    }

    /**
     * Name of the host provisioned via docker machine (string)
     * 
     */
    @Import(name="nodeName")
    private @Nullable Output<String> nodeName;

    /**
     * @return Name of the host provisioned via docker machine (string)
     * 
     */
    public Optional<Output<String>> nodeName() {
        return Optional.ofNullable(this.nodeName);
    }

    private ClusterInactiveHostArgs() {}

    private ClusterInactiveHostArgs(ClusterInactiveHostArgs $) {
        this.address = $.address;
        this.nodeName = $.nodeName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterInactiveHostArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterInactiveHostArgs $;

        public Builder() {
            $ = new ClusterInactiveHostArgs();
        }

        public Builder(ClusterInactiveHostArgs defaults) {
            $ = new ClusterInactiveHostArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param address Address of Bastion Host (string)
         * 
         * @return builder
         * 
         */
        public Builder address(@Nullable Output<String> address) {
            $.address = address;
            return this;
        }

        /**
         * @param address Address of Bastion Host (string)
         * 
         * @return builder
         * 
         */
        public Builder address(String address) {
            return address(Output.of(address));
        }

        /**
         * @param nodeName Name of the host provisioned via docker machine (string)
         * 
         * @return builder
         * 
         */
        public Builder nodeName(@Nullable Output<String> nodeName) {
            $.nodeName = nodeName;
            return this;
        }

        /**
         * @param nodeName Name of the host provisioned via docker machine (string)
         * 
         * @return builder
         * 
         */
        public Builder nodeName(String nodeName) {
            return nodeName(Output.of(nodeName));
        }

        public ClusterInactiveHostArgs build() {
            return $;
        }
    }

}
