// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetDebug(ctx *pulumi.Context) bool {
	v, err := config.TryBool(ctx, "rke:debug")
	if err == nil {
		return v
	}
	return getEnvOrDefault(false, parseEnvBool, "RKE_DEBUG").(bool)
}
func GetLogFile(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "rke:logFile")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "RKE_LOG_FILE").(string)
}
