// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudConfigBlockStorage;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudConfigGlobal;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudConfigLoadBalancer;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudConfigMetadata;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudConfigRoute;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterCloudProviderOpenstackCloudConfig {
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudConfigBlockStorage blockStorage;
    /**
     * @return (list maxitems:1)
     * 
     */
    private ClusterCloudProviderOpenstackCloudConfigGlobal global;
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudConfigLoadBalancer loadBalancer;
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudConfigMetadata metadata;
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudConfigRoute route;

    private ClusterCloudProviderOpenstackCloudConfig() {}
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudConfigBlockStorage> blockStorage() {
        return Optional.ofNullable(this.blockStorage);
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public ClusterCloudProviderOpenstackCloudConfigGlobal global() {
        return this.global;
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudConfigLoadBalancer> loadBalancer() {
        return Optional.ofNullable(this.loadBalancer);
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudConfigMetadata> metadata() {
        return Optional.ofNullable(this.metadata);
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudConfigRoute> route() {
        return Optional.ofNullable(this.route);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterCloudProviderOpenstackCloudConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ClusterCloudProviderOpenstackCloudConfigBlockStorage blockStorage;
        private ClusterCloudProviderOpenstackCloudConfigGlobal global;
        private @Nullable ClusterCloudProviderOpenstackCloudConfigLoadBalancer loadBalancer;
        private @Nullable ClusterCloudProviderOpenstackCloudConfigMetadata metadata;
        private @Nullable ClusterCloudProviderOpenstackCloudConfigRoute route;
        public Builder() {}
        public Builder(ClusterCloudProviderOpenstackCloudConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.blockStorage = defaults.blockStorage;
    	      this.global = defaults.global;
    	      this.loadBalancer = defaults.loadBalancer;
    	      this.metadata = defaults.metadata;
    	      this.route = defaults.route;
        }

        @CustomType.Setter
        public Builder blockStorage(@Nullable ClusterCloudProviderOpenstackCloudConfigBlockStorage blockStorage) {
            this.blockStorage = blockStorage;
            return this;
        }
        @CustomType.Setter
        public Builder global(ClusterCloudProviderOpenstackCloudConfigGlobal global) {
            this.global = Objects.requireNonNull(global);
            return this;
        }
        @CustomType.Setter
        public Builder loadBalancer(@Nullable ClusterCloudProviderOpenstackCloudConfigLoadBalancer loadBalancer) {
            this.loadBalancer = loadBalancer;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(@Nullable ClusterCloudProviderOpenstackCloudConfigMetadata metadata) {
            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder route(@Nullable ClusterCloudProviderOpenstackCloudConfigRoute route) {
            this.route = route;
            return this;
        }
        public ClusterCloudProviderOpenstackCloudConfig build() {
            final var _resultValue = new ClusterCloudProviderOpenstackCloudConfig();
            _resultValue.blockStorage = blockStorage;
            _resultValue.global = global;
            _resultValue.loadBalancer = loadBalancer;
            _resultValue.metadata = metadata;
            _resultValue.route = route;
            return _resultValue;
        }
    }
}
