// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rke.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudProviderBlockStorage;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudProviderGlobal;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudProviderLoadBalancer;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudProviderMetadata;
import com.pulumi.rke.outputs.ClusterCloudProviderOpenstackCloudProviderRoute;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterCloudProviderOpenstackCloudProvider {
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudProviderBlockStorage blockStorage;
    /**
     * @return (list maxitems:1)
     * 
     */
    private ClusterCloudProviderOpenstackCloudProviderGlobal global;
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudProviderLoadBalancer loadBalancer;
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudProviderMetadata metadata;
    /**
     * @return (list maxitems:1)
     * 
     */
    private @Nullable ClusterCloudProviderOpenstackCloudProviderRoute route;

    private ClusterCloudProviderOpenstackCloudProvider() {}
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudProviderBlockStorage> blockStorage() {
        return Optional.ofNullable(this.blockStorage);
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public ClusterCloudProviderOpenstackCloudProviderGlobal global() {
        return this.global;
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudProviderLoadBalancer> loadBalancer() {
        return Optional.ofNullable(this.loadBalancer);
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudProviderMetadata> metadata() {
        return Optional.ofNullable(this.metadata);
    }
    /**
     * @return (list maxitems:1)
     * 
     */
    public Optional<ClusterCloudProviderOpenstackCloudProviderRoute> route() {
        return Optional.ofNullable(this.route);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterCloudProviderOpenstackCloudProvider defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ClusterCloudProviderOpenstackCloudProviderBlockStorage blockStorage;
        private ClusterCloudProviderOpenstackCloudProviderGlobal global;
        private @Nullable ClusterCloudProviderOpenstackCloudProviderLoadBalancer loadBalancer;
        private @Nullable ClusterCloudProviderOpenstackCloudProviderMetadata metadata;
        private @Nullable ClusterCloudProviderOpenstackCloudProviderRoute route;
        public Builder() {}
        public Builder(ClusterCloudProviderOpenstackCloudProvider defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.blockStorage = defaults.blockStorage;
    	      this.global = defaults.global;
    	      this.loadBalancer = defaults.loadBalancer;
    	      this.metadata = defaults.metadata;
    	      this.route = defaults.route;
        }

        @CustomType.Setter
        public Builder blockStorage(@Nullable ClusterCloudProviderOpenstackCloudProviderBlockStorage blockStorage) {
            this.blockStorage = blockStorage;
            return this;
        }
        @CustomType.Setter
        public Builder global(ClusterCloudProviderOpenstackCloudProviderGlobal global) {
            this.global = Objects.requireNonNull(global);
            return this;
        }
        @CustomType.Setter
        public Builder loadBalancer(@Nullable ClusterCloudProviderOpenstackCloudProviderLoadBalancer loadBalancer) {
            this.loadBalancer = loadBalancer;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(@Nullable ClusterCloudProviderOpenstackCloudProviderMetadata metadata) {
            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder route(@Nullable ClusterCloudProviderOpenstackCloudProviderRoute route) {
            this.route = route;
            return this;
        }
        public ClusterCloudProviderOpenstackCloudProvider build() {
            final var o = new ClusterCloudProviderOpenstackCloudProvider();
            o.blockStorage = blockStorage;
            o.global = global;
            o.loadBalancer = loadBalancer;
            o.metadata = metadata;
            o.route = route;
            return o;
        }
    }
}
