// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Inputs
{

    public sealed class ClusterCloudProviderAwsCloudProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("global")]
        public Input<Inputs.ClusterCloudProviderAwsCloudProviderGlobalArgs>? Global { get; set; }

        [Input("serviceOverrides")]
        private InputList<Inputs.ClusterCloudProviderAwsCloudProviderServiceOverrideArgs>? _serviceOverrides;
        public InputList<Inputs.ClusterCloudProviderAwsCloudProviderServiceOverrideArgs> ServiceOverrides
        {
            get => _serviceOverrides ?? (_serviceOverrides = new InputList<Inputs.ClusterCloudProviderAwsCloudProviderServiceOverrideArgs>());
            set => _serviceOverrides = value;
        }

        public ClusterCloudProviderAwsCloudProviderArgs()
        {
        }
        public static new ClusterCloudProviderAwsCloudProviderArgs Empty => new ClusterCloudProviderAwsCloudProviderArgs();
    }
}
