// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Inputs
{

    public sealed class ClusterCloudProviderVsphereCloudConfigVirtualCenterGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// (string)
        /// </summary>
        [Input("datacenters", required: true)]
        public Input<string> Datacenters { get; set; } = null!;

        /// <summary>
        /// Name of virtualcenter config for Vsphere Cloud Provider config (string)
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Registry password (string)
        /// </summary>
        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        /// <summary>
        /// Port used for SSH communication (string)
        /// </summary>
        [Input("port")]
        public Input<string>? Port { get; set; }

        /// <summary>
        /// (int)
        /// </summary>
        [Input("soapRoundtripCount")]
        public Input<int>? SoapRoundtripCount { get; set; }

        /// <summary>
        /// Registry user (string)
        /// </summary>
        [Input("user", required: true)]
        public Input<string> User { get; set; } = null!;

        public ClusterCloudProviderVsphereCloudConfigVirtualCenterGetArgs()
        {
        }
    }
}
