// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Inputs
{

    public sealed class ClusterAuthenticationGetArgs : Pulumi.ResourceArgs
    {
        [Input("sans")]
        private InputList<string>? _sans;

        /// <summary>
        /// List of additional hostnames and IPs to include in the api server PKI cert (list)
        /// </summary>
        public InputList<string> Sans
        {
            get => _sans ?? (_sans = new InputList<string>());
            set => _sans = value;
        }

        /// <summary>
        /// Authentication strategy that will be used in RKE k8s cluster. Default: `x509` (string)
        /// </summary>
        [Input("strategy")]
        public Input<string>? Strategy { get; set; }

        /// <summary>
        /// Webhook configuration options (list maxitem: 1)
        /// </summary>
        [Input("webhook")]
        public Input<Inputs.ClusterAuthenticationWebhookGetArgs>? Webhook { get; set; }

        public ClusterAuthenticationGetArgs()
        {
        }
    }
}
