// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rke.Inputs
{

    public sealed class ClusterCloudProviderGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("awsCloudConfig")]
        public Input<Inputs.ClusterCloudProviderAwsCloudConfigGetArgs>? AwsCloudConfig { get; set; }

        /// <summary>
        /// AWS Cloud Provider config
        /// </summary>
        [Input("awsCloudProvider")]
        public Input<Inputs.ClusterCloudProviderAwsCloudProviderGetArgs>? AwsCloudProvider { get; set; }

        [Input("azureCloudConfig")]
        public Input<Inputs.ClusterCloudProviderAzureCloudConfigGetArgs>? AzureCloudConfig { get; set; }

        /// <summary>
        /// Azure Cloud Provider config
        /// </summary>
        [Input("azureCloudProvider")]
        public Input<Inputs.ClusterCloudProviderAzureCloudProviderGetArgs>? AzureCloudProvider { get; set; }

        [Input("customCloudConfig")]
        public Input<string>? CustomCloudConfig { get; set; }

        /// <summary>
        /// Custom Cloud Provider config
        /// </summary>
        [Input("customCloudProvider")]
        public Input<string>? CustomCloudProvider { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("openstackCloudConfig")]
        public Input<Inputs.ClusterCloudProviderOpenstackCloudConfigGetArgs>? OpenstackCloudConfig { get; set; }

        /// <summary>
        /// Openstack Cloud Provider config
        /// </summary>
        [Input("openstackCloudProvider")]
        public Input<Inputs.ClusterCloudProviderOpenstackCloudProviderGetArgs>? OpenstackCloudProvider { get; set; }

        [Input("vsphereCloudConfig")]
        public Input<Inputs.ClusterCloudProviderVsphereCloudConfigGetArgs>? VsphereCloudConfig { get; set; }

        /// <summary>
        /// Vsphere Cloud Provider config
        /// </summary>
        [Input("vsphereCloudProvider")]
        public Input<Inputs.ClusterCloudProviderVsphereCloudProviderGetArgs>? VsphereCloudProvider { get; set; }

        public ClusterCloudProviderGetArgs()
        {
        }
        public static new ClusterCloudProviderGetArgs Empty => new ClusterCloudProviderGetArgs();
    }
}
